spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: "${DB_PASSWORD}"
    url: jdbc:mysql://localhost:3306/dimo_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  #      &serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      ddl-auto: update
          ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

cloudinary:
  cloud-name: dsrmaoof8
  api-key: "${CLOUDINARY_KEY}"
  api-secret: "${CLOUDINARY_SECRET}"